# Generated by Django 2.0.7 on 2018-07-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toppings',
            name='topping',
            field=models.CharField(choices=[('PEPP', 'Pepperoni'), ('SAUS', 'Sausage'), ('MUSH', 'Mushrooms'), ('ONIO', 'Onions'), ('HAM', 'Ham'), ('CABA', 'Canadian Bacon'), ('PINE', 'Pineapple'), ('EGGP', 'Eggplant'), ('TOBA', 'Tomato & Basil'), ('GRPE', 'Green Peppers'), ('HAMB', 'Hamburger'), ('SPIN', 'Spinach'), ('ARTI', 'Artichoke'), ('BUCH', 'Buffalo Chicken'), ('BACH', 'Barbecue Chicken'), ('ANCH', 'Anchovies'), ('BLOL', 'Black Olives'), ('FRGA', 'Fresh Garlic'), ('ZUCC', 'Zucchini')], max_length=4),
        ),
    ]
