# Generated by Django 2.0.7 on 2018-07-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('orders', '0002_auto_20180726_0248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CHEE', 'Cheese'), ('ITAL', 'Italian'), ('HACH', 'Ham + Cheese'), ('MEBA', 'Meatball'), ('TUNA', 'Tuna'), ('TURK', 'Turkey'), ('CHPA', 'Chicken Parmigiana'), ('EGPA', 'Eggplant Parmigiana'), ('STEA', 'Steak'), ('STCH', 'Steak + Cheese'), ('SCMU', 'Steak + Cheese + Mushrooms'), ('SCGP', 'Steak + Cheese + Green Peppers'), ('SCON', 'Steak + Cheese + Onions'), ('SAPO', 'Sausage, Peppers & Onions'), ('HAMB', 'Hamburger'), ('CHBU', 'Cheeseburger'), ('FRCH', 'Fried Chicken'), ('VEGG', 'Veggie')], max_length=4, verbose_name='What is on the sub?')),
                ('large', models.BooleanField(verbose_name='Is it a large sub?')),
                ('extra_cheese', models.BooleanField(verbose_name='Is extra cheese added?')),
            ],
        ),
        migrations.RenameModel(
            old_name='Toppings',
            new_name='Topping',
        ),
        migrations.DeleteModel(
            name='Subs',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='num_toppings',
        ),
        migrations.AlterField(
            model_name='dinner_platter',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Type of dinner platter?'),
        ),
        migrations.AlterField(
            model_name='pasta',
            name='name',
            field=models.CharField(choices=[('MOZZ', 'Baked Ziti w/Mozzarella'), ('MEBA', 'Baked Ziti w/Meatballs\t'), ('CHIC', 'Baked Ziti w/Chicken')], max_length=4, verbose_name='Mozzarella, meatballs or chicken?'),
        ),
        migrations.AlterField(
            model_name='salad',
            name='name',
            field=models.CharField(choices=[('GARD', 'Garden Salad'), ('GREE', 'Greek Salad'), ('ANPA', 'Antipasto'), ('TUNA', 'Salad with Tuna')], max_length=4, verbose_name='Type of salad?'),
        ),
    ]
