# Generated by Django 2.0.7 on 2018-07-28 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_auto_20180727_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('SUB', 'Sub'), ('PAST', 'Pasta'), ('SALA', 'Salad'), ('DIPL', 'Dinner Plate'), ('SIPI', 'Sicilian Pizza'), ('REPI', 'Regular Pizza')], max_length=4, verbose_name='What kind of item is this?')),
                ('choice', models.CharField(max_length=64, verbose_name='What flavor is it?')),
                ('size', models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=2, verbose_name='What size item is this?')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='What does it cost?')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ordered_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('SUB', 'Sub'), ('PAST', 'Pasta'), ('SALA', 'Salad'), ('DIPL', 'Dinner Plate'), ('SIPI', 'Sicilian Pizza'), ('REPI', 'Regular Pizza')], max_length=4, verbose_name='What kind of item is this?')),
                ('choice', models.CharField(max_length=64, verbose_name='What flavor is it?')),
                ('size', models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=2, verbose_name='What size item is this?')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='What does it cost?')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
        ),
        migrations.DeleteModel(
            name='Dinner_Platter',
        ),
        migrations.DeleteModel(
            name='Pasta',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
        migrations.DeleteModel(
            name='Salad',
        ),
        migrations.DeleteModel(
            name='Sub',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
    ]
