# Generated by Django 2.0.7 on 2018-07-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20180729_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='topping',
            field=models.CharField(max_length=64),
        ),
    ]
