# Generated by Django 2.0.7 on 2018-07-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20180729_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='num_toppings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='menu',
            name='choice',
            field=models.CharField(blank=True, max_length=64, verbose_name='What flavor is it?'),
        ),
        migrations.AlterField(
            model_name='ordered_item',
            name='choice',
            field=models.CharField(blank=True, max_length=64, verbose_name='What flavor is it?'),
        ),
    ]
