# Generated by Django 2.0.7 on 2018-07-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20180729_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='toppings',
        ),
        migrations.AddField(
            model_name='ordered_item',
            name='num_toppings',
            field=models.IntegerField(default=0),
        ),
    ]
