# Generated by Django 2.0.7 on 2018-07-30 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20180729_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('L', 'Large')], max_length=2, verbose_name='What size item is this?'),
        ),
        migrations.AlterField(
            model_name='ordered_item',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('L', 'Large')], max_length=2, verbose_name='What size item is this?'),
        ),
    ]
